PUT https://localhost:5001/api/customers/EPTA HTTP/1.1
Content-Type: application/json
Content-Length: 351

{
    "customerID": "EPTAA",
    "companyName": "Simple Company Incorporated",
    "contactName": "Viktor Stomatin",
    "contactTitle": "Mister",
    "address": "Wall Street",
    "city": "New York",
    "region": "NY",
    "postalCode": "90210",
    "country": "USA",
    "phone": "(123) 555-1234",
    "fax": null,
    "orders": 
    {
        "OrderId" : "",
    }
}
